spring.application.name=StudentRegistrationApp

server.port = 2323

server.servlet.context-path =/student
app.version=1.0

# PostgreSQL database configuration
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Limit connections to 2
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=2


# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# application.properties
logging.level.root=INFO
logging.level.com.example.mypackage=DEBUG

######## Swagger Configuration #################################
# Custom UI path
springdoc.swagger-ui.path=/swagger
# Custom OpenAPI JSON path
springdoc.api-docs.path=/api-docs

######### mail ##############
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kr.vijaygupta01@gmail.com
spring.mail.password=ugpa avmy bcik tilc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.graphql.graphiql.enabled=true
